# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
# Do npm manually, as "node" also does Yarn and pnpm
disable = ["containers", "git_repos", "node"]

# Display the time in step titles
display_time = false

# Cleanup temporary or old files
cleanup = true
